### ISSUE TITLE
3/24イベント

### ISSUE THREAD

**Issue by yusukesugasawa** [roppongirb/discussions#42]

**Comment by hatappi** [comment]
とりあえず次回はこれ確定〜〜〜〜〜
https://github.com/roppongirb/discussions/issues/47

**Comment by hatappi** [comment]
アンケート！！
https://docs.google.com/forms/d/e/1FAIpQLSfN6wZXw7Dr55XsTa0LS0FPW-Ck-Lk0zrV9mx7idLY68Q9FOg/viewform
